### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by ZairiAimenDz** [4Annee/Online-Examination-System#1]
Create the Activity Diagram For the Specific Usecases

**Comment by ZairiAimenDz** [comment]
@Wailouahab  @agentHisoka 
--------------------------
Exam Passing Activity Diagram (Interaction between student & system) :
- Be Online 10 Minutes Before The Exam 
- Authentication
- Loop :
   - Choose Qt
   - Answer Qt
   - Submit Response 
 - Submit The Exam For Correction 
 - After Exam Time is Finished The PC Calculated Grade will be sent by Email and shown in student dashboard
 ----------------------------
Exam Creation Activity Diagram (Teacher - System - Student ): 
- Name The Exam
- Select The Type ( Exam / Test or Assessment / Homework )
- Select The Start / End Date
- Loop : 
  - Choose Qt Type
  - Fill The Qt Details / Description
  - Add The Correct Answer
- Submit The Final Exam For Review
- When Accepted Students Get Notified With The Start/End Date

-----------------------------
Exam Score Management Activity Diagram (Teacher - System - Student): 
- Loop :
  - Select A Student Exam Submission ( Can Be Ordered By Highest Score or whatever )
  - System Shows Wrong or Uncorrected Answer Submission
  - Loop :
      - Check Answer
      - Give Score
  - Submit The Result 
- Submit All The Results 
------------------------------

**Comment by agentHisoka** [comment]
check

Le dim. 13 mars 2022 à 15:29, Aimen Zairi ***@***.***> a
écrit :

**Comment by agentHisoka** [comment]
first Diagramme
