### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by ZairiAimenDz** [4Annee/Online-Examination-System#2]
Create a Class Diagram For the Project

**Comment by ZairiAimenDz** [comment]
Aid For Class Diagram :
- User : Teacher :
     - Exams : id, start time, end time, list of Questions
     - Questions : id, qt, description (has subtypes : Code, Text, MCQ which has multiple options … will be decided later), correct answer ... to be discussed.
- User : Student :
     -  Passed Exams (Table Defining the many to many relation between Exam and Student ) : Primary Key (id student + id exam ) , Final Score, List of Student Answers
     -  Student Answers : PK (id stud, id qt, id exam), answer, score
    
Draw this then we will improve upon it once needed.

@NadjetBoumezoued 


![Class Diagram User Service](https://user-images.githubusercontent.com/42500714/157481057-ca29eab3-9ff9-4ac3-a995-de5632c3d293.png)

**Comment by NadjetBoumezoued** [comment]
![Class Diagram](https://user-images.githubusercontent.com/82460270/157739880-b29e2426-f781-4eb0-b217-45966d2a6613.png)

@ZairiAimenDz

**Comment by ZairiAimenDz** [comment]
Thank you, good work, please send the astah file as well. (using email)
